### ISSUE TITLE
BUG: Page not found when apply or delete changes in a workspace via the icons

### ISSUE THREAD

**Issue by crydotsnake** [Sebobo/Shel.Neos.WorkspaceModule#16]
If I want to publish or delete a single change in a workspace where I have several changes on one page, using the respective icons (see screenshot), I am redirected to a "Page not Found" page in the frontend.

![Bildschirmfoto 2022-09-19 um 16 18 12](https://user-images.githubusercontent.com/39345336/191039727-1ace315a-7b90-4611-9dfa-07bb3f7882eb.png)

### Steps to reproduce

1. Make multiple changes on a page
2. Review your workspace
3. Try to delete, or publish one change via the respective icons.

### Expected Behavior

My changes should either be deleted or published. Depending on what icon I choose.

### Actual Behavior

I am redirected to a Page Not Found page in the frontend.

**Comment by Sebobo** [comment]
I assume this is a missing policy. Can you check if there is a helpful entry in the logs?

**Comment by crydotsnake** [comment]
> I assume this is a missing policy. Can you check if there is a helpful entry in the logs?

Not really 😕 

`System_Development.log`:

```
22-09-19 18:17:42 16118      DEBUG                          Session: Resumed session with id NVJlPfTv20kmWCr4oakzae8GWE3vV3jc which was inactive for 3 minutes. (210s)
22-09-19 18:17:42 16118      DEBUG                          Router route(): A cached Route with the cache identifier "5075f61458e8be8d800b4a1e67912a06" matched the request "http://127.0.0.1:8081/neos/management/workspaces?moduleArguments%5B%40package%5D=shel.neos.workspacemodule&moduleArguments%5B%40controller%5D=workspaces&moduleArguments%5B%40action%5D=publishnode&moduleArguments%5B%40format%5D=html&moduleArguments%5Bnode%5D=%2Fsites%2Fneosdemo%2Fmain%2Fnode-w38s0sqp2v82t%40private-workspace-4z08o%3Blanguage%3Den_US&moduleArguments%5BselectedWorkspace%5D%5B__identity%5D=private-workspace-4z08o (POST)".
22-09-19 18:17:42 16118      DEBUG                          CSRF: Successfully verified token for Neos\Neos\Controller\Backend\ModuleController::indexAction()
22-09-19 18:17:42 16118      DEBUG                          CSRF: Successfully verified token for Shel\Neos\WorkspaceModule\Controller\WorkspacesController::publishNodeAction()
```

I also tried to use the developer tools of the browser to find out where the problem lies. But even there I did not get any further.

**Comment by crydotsnake** [comment]
I started a new debug session. The exception is:

```
Page Not Found
Sorry, the page you requested was not found.

Access denied for method Method: Neos\Neos\Controller\Module\Management\WorkspacesController::publishNodeAction() Evaluated following 1 privilege target(s): "Neos.Neos:AllControllerActions": ABSTAIN (0 granted, 0 denied, 1 abstained) Authenticated roles: Neos.Flow:Everybody, Neos.Flow:AuthenticatedUser, Neos.Neos:Editor, Neos.Neos:AbstractEditor, Neos.ContentRepository:Administrator, Neos.ContentRepository:InternalWorkspaceAccess, Neos.Neos:LivePublisher, Neos.Neos:Administrator
```

And when you discard a change:

```
Access denied for method Method: Neos\Neos\Controller\Module\Management\WorkspacesController::discardNodeAction() Evaluated following 1 privilege target(s): "Neos.Neos:AllControllerActions": ABSTAIN (0 granted, 0 denied, 1 abstained) Authenticated roles: Neos.Flow:Everybody, Neos.Flow:AuthenticatedUser, Neos.Neos:RestrictedEditor, Neos.Neos:AbstractEditor, Neos.ContentRepository:Administrator, Neos.ContentRepository:InternalWorkspaceAccess
```


Edit:

By the way, the problem also occurs when you install the module in a fresh Neos installation

**Comment by crydotsnake** [comment]
The problem was that the two methods `discardNodeAction` and `publishNodeAction` in the `privilegeTargets` `Shel.Neos.WorkspaceModule:Backend.WorkspaceController` could not be called because there where not defined.
