### ISSUE TITLE
Bug: Edit and delete buttons throw error

### ISSUE THREAD

**Issue by pKallert** [Sebobo/Shel.Neos.WorkspaceModule#21]
### Description
While the workspace changes are loading, clicking on the "Edit workspace" or "Delete workspace" buttons throw errors.

### Steps to Reproduce

1. Have a lot of workspace changes / slow internet
2. Load worspace overview page so that loading icons for workspace changes are shown
3. Click on "Edit workspace" or "Delete workspace"

#### Expected behavior
Either the buttons should be disabled while the page is loading or the delete and edit functions should work (not sure if this is doable)

#### Actual behavior

An error is shown in the text: 

![workspace_change](https://user-images.githubusercontent.com/91674611/210563004-3febe3f6-1626-40b3-be4d-89425d06db24.gif)

For deleting JS errors are thrown here: 
https://github.com/Sebobo/Shel.Neos.WorkspaceModule/blob/main/Resources/Private/JavaScript/components/dialogs/DeleteWorkspaceDialog.tsx#L48

For editing JS errors are thrown here:
https://github.com/Sebobo/Shel.Neos.WorkspaceModule/blob/main/Resources/Private/JavaScript/components/dialogs/EditWorkspaceDialog.tsx#L161

**Comment by Sebobo** [comment]
Thx. I disable the edit button until all changes are loaded as they are required for the dialog
