### ISSUE TITLE
Could not restore impersonated user inside the workspace module

### ISSUE THREAD

**Issue by markusguenther** [Sebobo/Shel.Neos.WorkspaceModule#30]
If you use the user impersonation, you cannot restore the user when you're inside the new workspace module.
It work in the classical module.

The request is forbidden.
![Screenshot 2023-02-23 at 13 23 47](https://user-images.githubusercontent.com/1014126/220905112-55079fc6-6ea2-49f2-8e05-04aded079299.png)

**Comment by crydotsnake** [comment]
Could this be an issue with the privileges that comes with the workspace module?
Will take a look at this.

**Comment by crydotsnake** [comment]
Strangely, the error only occurs when the user account you want to switch back from is not an administrator. So if the account has the editor role for example, it fails. But if the account has the administrator role, it works.

![2023-08-21_17-19](https://github.com/Sebobo/Shel.Neos.WorkspaceModule/assets/39345336/50eac6e7-0042-4663-8136-a1605463c74f)

**Comment by crydotsnake** [comment]
I played a bit with the Privileges but coulnt find the issue so far.

**Comment by markusguenther** [comment]
To be honest, I forgot that issue :D 
Need to dive deeper as well.

**Comment by so-grimm** [comment]
Hi,
Is there any update on this issue? Installed the package this morning and just encountered this problem too.

It works fine if I add the privilegeTarget 'Neos.Neos:Impersonate' to a role, but I would prefer not to do that for every role, especially since I'm not sure if that has any negative side effects.

**Comment by markusguenther** [comment]
Sadly not, as I did not look into it so far :/

**Comment by Sebobo** [comment]
This happens due to Neos reading the `data-csrf-token` attribute and this plugin providing it, but json encoded, leading the APIService to use my token instead of the one designated for the backend. I can fix this here, but we should also probably have a more unique selector for the backend token.

**Comment by Sebobo** [comment]
Related core issue https://github.com/neos/neos-development-collection/issues/4822

**Comment by so-grimm** [comment]
Thanks for looking into it and creating a core issue!
