### ISSUE TITLE
BUG: Error when trying to delete a user

### ISSUE THREAD

**Issue by so-grimm** [Sebobo/Shel.Neos.WorkspaceModule#34]
**Steps to reproduce:**

- Install package in a Neos system with several user accounts
- go to User Management
- click on the delete icon of any user and confirm you want to delete

**Error Message:**
```
An exception occurred while executing 'DELETE FROM neos_contentrepository_domain_model_workspace WHERE name = ?' with params ["user-redakteur"]

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`<db-name>`.`shel_neos_workspacemodule_domain_model_workspacedetails`, CONSTRAINT `FK_923CCEA8D940019` FOREIGN KEY (`workspace`) REFERENCES `neos_contentrepository_domain_model_workspace` (`)
```

**Additional Information:**

- Neos: ~8.3.0
- PHP: ^8.2
- shel/neos-workspace-module: 1.0.0

**Comment by Sebobo** [comment]
Should be fine now with release 1.0.1

**Comment by Sebobo** [comment]
Btw. the "delete user" keywords were the relevant one here. For some reason, deleting a workspace worked fine. I don't actually know what the difference is as the deletion of the user triggers the deletion of the workspace 🤷🏻‍♂️
So thanks for a good description!
